apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-python-server
  labels:
    app: homelab-python-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homelab-python-server
  template:
    metadata:
      labels:
        app: homelab-python-server
    spec:
      containers:
      - name: python-server
        image: homelab-python-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: APP_NAME
          value: "Homelab Python Server"
        - name: APP_VERSION
          value: "1.0.0"
        - name: ROOT_PATH
          value: "/api"
        - name: ENABLE_ENV_ENDPOINT
          value: "true"
        - name: REDACT_SENSITIVE_ENV_VARS
          value: "true"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: homelab-python-server-service
  labels:
    app: homelab-python-server
spec:
  selector:
    app: homelab-python-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-python-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: python-server.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: homelab-python-server-service
            port:
              number: 80 