apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-config
  namespace: homelab
data:
  # Frontend configuration
  NODE_ENV: "production"
  VITE_API_TIMEOUT: "10000"
  VITE_DEV_MODE: "false"
  
  # Backend configurations
  PYTHON_PORT: "8080"
  NODE_PORT: "5000"
  
  # Service URLs (for internal communication)
  PYTHON_SERVICE_URL: "http://python-service:8080"
  NODE_SERVICE_URL: "http://node-service:5000" 