apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homelab

resources:
- namespace.yaml
- configmap.yaml
- server-python-deployment.yaml
- server-node-deployment.yaml
- client-dual-deployment.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: homelab
  app.kubernetes.io/part-of: mlops-practice
  app.kubernetes.io/managed-by: kustomize 