apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-python
  namespace: homelab
  labels:
    app: server-python
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-python
  template:
    metadata:
      labels:
        app: server-python
        component: backend
    spec:
      containers:
      - name: server-python
        image: server-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: APP_NAME
          value: "Homelab Python Server"
        - name: APP_VERSION
          value: "1.0.0"
        - name: ROOT_PATH
          value: "/"
        - name: ENABLE_ENV_ENDPOINT
          value: "true"
        - name: REDACT_SENSITIVE_ENV_VARS
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: server-python
  namespace: homelab
  labels:
    app: server-python
    component: backend
spec:
  selector:
    app: server-python
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 